# Generated by Django 4.2.11 on 2026-05-26 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import patients.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=patients.models._upload_patient_photo)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_primary', models.CharField(max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_dentist', models.ForeignKey(blank=True, limit_choices_to={'role': 'dentist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('xray', 'X-Ray'), ('photo', 'Clinical Photo'), ('consent', 'Consent Form'), ('id', 'ID Document'), ('insurance', 'Insurance'), ('lab', 'Lab Report'), ('referral', 'Referral'), ('prescription', 'Prescription'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=patients.models._upload_patient_doc)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypertension', models.BooleanField(default=False)),
                ('diabetes', models.CharField(choices=[('none', 'None'), ('type1', 'Type 1'), ('type2', 'Type 2'), ('pre', 'Pre-diabetic')], default='none', max_length=10)),
                ('heart_disease', models.BooleanField(default=False)),
                ('heart_disease_details', models.TextField(blank=True)),
                ('bleeding_disorder', models.BooleanField(default=False)),
                ('bleeding_disorder_details', models.TextField(blank=True)),
                ('epilepsy', models.BooleanField(default=False)),
                ('hepatitis', models.CharField(choices=[('none', 'None'), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='none', max_length=5)),
                ('hiv_positive', models.BooleanField(default=False)),
                ('respiratory_conditions', models.TextField(blank=True)),
                ('kidney_disease', models.BooleanField(default=False)),
                ('thyroid_conditions', models.TextField(blank=True)),
                ('osteoporosis', models.BooleanField(default=False)),
                ('current_medications', models.TextField(blank=True)),
                ('on_blood_thinners', models.BooleanField(default=False)),
                ('on_bisphosphonates', models.BooleanField(default=False)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('pregnancy_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('other_conditions', models.TextField(blank=True)),
                ('previous_surgeries', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_medical_history',
            },
        ),
        migrations.CreateModel(
            name='DentalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_dentist', models.CharField(blank=True, max_length=200)),
                ('last_visit_date', models.DateField(blank=True, null=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('prev_extractions', models.BooleanField(default=False)),
                ('prev_orthodontics', models.BooleanField(default=False)),
                ('prev_implants', models.BooleanField(default=False)),
                ('prev_root_canal', models.BooleanField(default=False)),
                ('prev_dentures', models.BooleanField(default=False)),
                ('prev_whitening', models.BooleanField(default=False)),
                ('prev_treatment_details', models.TextField(blank=True)),
                ('pain_sensitivity', models.BooleanField(default=False)),
                ('sensitivity_details', models.TextField(blank=True)),
                ('bleeding_gums', models.BooleanField(default=False)),
                ('dry_mouth', models.BooleanField(default=False)),
                ('jaw_pain', models.BooleanField(default=False)),
                ('brushing_frequency', models.CharField(choices=[('once', 'Once daily'), ('twice', 'Twice daily'), ('three', '3× daily'), ('rarely', 'Rarely')], default='twice', max_length=10)),
                ('flossing_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('never', 'Never')], default='weekly', max_length=10)),
                ('uses_mouthwash', models.BooleanField(default=False)),
                ('uses_electric_toothbrush', models.BooleanField(default=False)),
                ('is_smoker', models.BooleanField(default=False)),
                ('smoking_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('consumes_alcohol', models.BooleanField(default=False)),
                ('grinds_teeth', models.BooleanField(default=False)),
                ('nail_biting', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dental_history', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_dental_history',
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_type', models.CharField(choices=[('drug', 'Drug'), ('latex', 'Latex'), ('food', 'Food'), ('anesthesia', 'Anesthesia'), ('metal', 'Metal'), ('other', 'Other')], max_length=20)),
                ('substance', models.CharField(max_length=200)),
                ('reaction', models.CharField(max_length=500)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Allergies',
                'db_table': 'patient_allergies',
                'ordering': ['-severity'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='patients_last_na_ce6411_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone_primary'], name='patients_phone_p_5b9bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_active'], name='patients_is_acti_4a96f9_idx'),
        ),
    ]
