# Generated by Django 4.2.11 on 2026-05-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='country',
            new_name='nationality',
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('passing_by', 'Passing By'), ('instagram', 'Instagram'), ('google', 'Google'), ('friends', 'Friends'), ('others', 'Others')], max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='patients/signatures/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='social_media',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='temperature',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='wants_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='xray_collected',
            field=models.BooleanField(default=False),
        ),
    ]
