# Generated by Django 4.2.11 on 2026-06-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_country_patient_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ortho_interval_weeks',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Usually 6 or 8 weeks for braces patients', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_category',
            field=models.CharField(choices=[('general', 'General Dentistry'), ('orthodontic', 'Orthodontic'), ('both', 'General + Orthodontic')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_reminder_method',
            field=models.CharField(blank=True, choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('call', 'Phone Call'), ('email', 'Email')], max_length=20),
        ),
    ]
