# Generated by Django 4.2.11 on 2026-07-16 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0003_patient_ortho_interval_weeks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdocument',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='linked_module',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='linked_record_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='document_type',
            field=models.CharField(choices=[('consent', 'Consent'), ('referral', 'Referral'), ('radiograph', 'Radiograph'), ('lab_report', 'Lab Report'), ('identification', 'Identification'), ('orthodontic', 'Orthodontic'), ('clinical', 'Clinical'), ('photograph', 'Photograph'), ('general', 'General'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='PatientCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('phone', 'Phone call'), ('sms', 'SMS'), ('email', 'Email'), ('letter', 'Letter'), ('in_person', 'In-person discussion')], db_index=True, max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('outcome', models.CharField(blank=True, max_length=255)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='tasks.task')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='patients.patient')),
                ('staff_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_communications',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
