# Generated by Django 4.2.11 on 2026-07-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patientdocument_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDailySequence',
            fields=[
                ('sequence_date', models.DateField(primary_key=True, serialize=False)),
                ('last_sequence', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'patient_daily_sequences',
            },
        ),
    ]
