# Generated by Django 4.2.11 on 2026-08-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_archive_reason_user_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dentist', 'Dentist'), ('assistant', 'Assistant'), ('receptionist', 'Receptionist'), ('nurse', 'Nurse'), ('backoffice', 'Backoffice Staff')], default='assistant', max_length=20),
        ),
    ]
