# Generated by Django 4.2.11 on 2026-07-15 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('report_type', models.CharField(choices=[('executive', 'Executive Dashboard'), ('appointments', 'Appointments'), ('patients', 'Patients'), ('clinical', 'Clinical'), ('orthodontics', 'Orthodontics'), ('inventory', 'Inventory'), ('staff', 'Staff Productivity')], max_length=40)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('is_shared', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', 'report_type'], name='reports_sav_owner_i_073700_idx'), models.Index(fields=['is_shared', 'report_type'], name='reports_sav_is_shar_4c1663_idx')],
            },
        ),
    ]
