# Generated by Django 4.2.11 on 2026-06-04 11:20

import clinical.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_rename_country_patient_nationality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToothChart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dentition_type', models.CharField(choices=[('adult', 'Adult'), ('mixed', 'Mixed'), ('primary', 'Primary')], default='adult', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_chart', to='patients.patient')),
            ],
            options={
                'db_table': 'tooth_charts',
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=15)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dentist', models.ForeignKey(limit_choices_to={'role': 'dentist'}, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='patients.patient')),
            ],
            options={
                'db_table': 'treatment_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tooth_number', models.PositiveSmallIntegerField(blank=True, choices=[(11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (51, '51'), (52, '52'), (53, '53'), (54, '54'), (55, '55'), (61, '61'), (62, '62'), (63, '63'), (64, '64'), (65, '65'), (71, '71'), (72, '72'), (73, '73'), (74, '74'), (75, '75'), (81, '81'), (82, '82'), (83, '83'), (84, '84'), (85, '85')], null=True)),
                ('surfaces', models.CharField(blank=True, help_text='e.g. MOD', max_length=10)),
                ('procedure_name', models.CharField(max_length=200)),
                ('procedure_code', models.CharField(blank=True, help_text='CDT / ADA code', max_length=20)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined')], db_index=True, default='pending', max_length=15)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('elective', 'Elective')], default='normal', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinical.treatmentplan')),
            ],
            options={
                'db_table': 'treatment_plan_items',
                'ordering': ['sort_order', 'priority', 'tooth_number'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('note_type', models.CharField(choices=[('examination', 'Examination'), ('diagnosis', 'Diagnosis'), ('treatment', 'Treatment'), ('follow_up', 'Follow-up'), ('referral', 'Referral'), ('medication', 'Medication'), ('general', 'General')], db_index=True, default='general', max_length=20)),
                ('tooth_number', models.PositiveSmallIntegerField(blank=True, choices=[(11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (51, '51'), (52, '52'), (53, '53'), (54, '54'), (55, '55'), (61, '61'), (62, '62'), (63, '63'), (64, '64'), (65, '65'), (71, '71'), (72, '72'), (73, '73'), (74, '74'), (75, '75'), (81, '81'), (82, '82'), (83, '83'), (84, '84'), (85, '85')], db_index=True, null=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('clinical_findings', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_performed', models.TextField(blank=True)),
                ('materials_used', models.TextField(blank=True)),
                ('anesthesia_given', models.BooleanField(default=False)),
                ('anesthesia_type', models.CharField(blank=True, max_length=100)),
                ('next_visit_instructions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('note_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='patients.patient')),
            ],
            options={
                'db_table': 'clinical_notes',
                'ordering': ['-note_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('tooth_number', models.PositiveSmallIntegerField(blank=True, choices=[(11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (51, '51'), (52, '52'), (53, '53'), (54, '54'), (55, '55'), (61, '61'), (62, '62'), (63, '63'), (64, '64'), (65, '65'), (71, '71'), (72, '72'), (73, '73'), (74, '74'), (75, '75'), (81, '81'), (82, '82'), (83, '83'), (84, '84'), (85, '85')], null=True)),
                ('image_type', models.CharField(choices=[('periapical', 'Periapical X-ray'), ('bitewing', 'Bitewing X-ray'), ('panoramic', 'Panoramic X-ray'), ('cbct', 'CBCT / 3D Scan'), ('cephalometric', 'Cephalometric'), ('intraoral_photo', 'Intraoral Photo'), ('extraoral_photo', 'Extraoral Photo'), ('study_model', 'Study Model'), ('other', 'Other')], default='periapical', max_length=20)),
                ('image', models.ImageField(upload_to=clinical.models._upload_clinical_image)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('taken_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinical_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='clinical.clinicalnote')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_images', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinical_images',
                'ordering': ['-taken_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToothRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tooth_number', models.PositiveSmallIntegerField(choices=[(11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (51, '51'), (52, '52'), (53, '53'), (54, '54'), (55, '55'), (61, '61'), (62, '62'), (63, '63'), (64, '64'), (65, '65'), (71, '71'), (72, '72'), (73, '73'), (74, '74'), (75, '75'), (81, '81'), (82, '82'), (83, '83'), (84, '84'), (85, '85')], db_index=True)),
                ('condition', models.CharField(choices=[('healthy', 'Healthy'), ('caries', 'Caries'), ('filled', 'Filled'), ('crown', 'Crown'), ('missing', 'Missing'), ('implant', 'Implant'), ('bridge_anchor', 'Bridge Anchor'), ('bridge_pontic', 'Bridge Pontic'), ('rct', 'Root Canal Treated'), ('fractured', 'Fractured'), ('impacted', 'Impacted'), ('extracted', 'Extracted'), ('watch', 'Watch')], default='healthy', max_length=20)),
                ('surface_conditions', models.JSONField(blank=True, default=dict)),
                ('mobility_grade', models.PositiveSmallIntegerField(blank=True, help_text='0–3 Miller mobility scale', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('pocket_depth', models.JSONField(blank=True, default=dict, help_text="Dict of surface → mm, e.g. {'MB':4,'B':3,'DB':4,'ML':3,'L':2,'DL':3}")),
                ('furcation', models.CharField(blank=True, choices=[('', 'None'), ('I', 'Class I'), ('II', 'Class II'), ('III', 'Class III')], max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teeth', to='clinical.toothchart')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tooth_records',
                'ordering': ['tooth_number'],
                'unique_together': {('chart', 'tooth_number')},
            },
        ),
    ]
