# Generated by Django 4.2.11 on 2026-06-23 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_ortho_interval_weeks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalnote',
            name='tooth_number',
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='family_social_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='general_examination',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='medical_dental_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='orofacial_examination',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='tooth_numbers',
            field=models.JSONField(blank=True, default=list, help_text='Example: [22, 26, 36]'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='treatment_planned',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='RecallSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recall_type', models.CharField(choices=[('preventive', 'Preventive Recall'), ('orthodontic', 'Orthodontic Review'), ('custom', 'Custom Follow-up')], max_length=20)),
                ('due_date', models.DateField(db_index=True)),
                ('interval_days', models.PositiveIntegerField(help_text='180 = 6 months, 42 = 6 weeks, 56 = 8 weeks')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinical_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recall_schedules', to='clinical.clinicalnote')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_schedules', to='patients.patient')),
            ],
            options={
                'db_table': 'recall_schedules',
                'ordering': ['due_date'],
            },
        ),
    ]
