# Generated by Django 4.2.11 on 2026-07-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_remove_clinicalnote_tooth_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('chief_complaint', 'Chief Complaint'), ('medical_dental_history', 'Medical / Dental History'), ('family_social_history', 'Family / Social History'), ('clinical_findings', 'Clinical Findings'), ('general_examination', 'General Examination'), ('orofacial_examination', 'Orofacial Examination'), ('diagnosis', 'Diagnosis'), ('treatment_planned', 'Treatment Planned'), ('treatment_performed', 'Treatment Performed'), ('materials_used', 'Materials Used'), ('next_visit_instructions', 'Next Visit Instructions')], max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto Learned')], default='manual', max_length=20)),
                ('usage_count', models.IntegerField(default=1)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['template_type', '-usage_count', '-last_used', 'sort_order', 'label'],
            },
        ),
    ]
