# Generated by Django 4.2.11 on 2026-07-05 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_ortho_interval_weeks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinical', '0003_clinicaltemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrthodonticCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_type', models.CharField(max_length=100)),
                ('stage', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retention', 'Retention'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('estimated_completion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ortho_cases', to='patients.patient')),
                ('primary_dentist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrthodonticVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('upper_wire', models.CharField(blank=True, max_length=100)),
                ('lower_wire', models.CharField(blank=True, max_length=100)),
                ('procedures', models.JSONField(default=list)),
                ('compliance', models.CharField(blank=True, choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('next_review_days', models.IntegerField(default=42)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dentist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ortho_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clinical.orthodonticcase')),
            ],
        ),
    ]
