# Generated by Django 4.2.11 on 2026-07-15 12:16

import clinical.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinical', '0004_orthodonticcase_orthodonticvisit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orthodonticcase',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orthodonticvisit',
            options={'ordering': ['-visit_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='orthodonticcase',
            name='primary_dentist',
        ),
        migrations.AddField(
            model_name='orthodonticcase',
            name='appliances',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orthodonticcase',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orthodonticcase',
            name='chief_complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orthodonticcase',
            name='clinical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orthodonticcase',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orthodonticcase',
            name='estimated_duration_months',
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='orthodonticcase',
            name='malocclusion_classification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orthodonticcase',
            name='measurements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orthodonticcase',
            name='milestones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='orthodonticcase',
            name='treatment_objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orthodonticcase',
            name='treatment_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orthodonticcase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orthodonticvisit',
            name='appliance_changes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orthodonticvisit',
            name='clinical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orthodonticvisit',
            name='measurements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orthodonticvisit',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orthodonticvisit',
            name='procedures_performed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orthodonticvisit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orthodonticvisit',
            name='visit_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('records', 'Diagnostic Records'), ('bonding', 'Bonding'), ('adjustment', 'Adjustment'), ('wire_change', 'Wire Change'), ('elastic_review', 'Elastic Review'), ('repair', 'Appliance Repair'), ('debond', 'Debond'), ('retention', 'Retention Review'), ('review', 'Review'), ('completed', 'Completed')], default='adjustment', max_length=30),
        ),
        migrations.AlterField(
            model_name='orthodonticcase',
            name='appliance_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='orthodonticcase',
            name='stage',
            field=models.CharField(blank=True, default='Initial Consultation', max_length=100),
        ),
        migrations.AlterField(
            model_name='orthodonticcase',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('retention', 'Retention'), ('completed', 'Completed'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='OrthodonticPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('before', 'Before'), ('progress', 'Progress'), ('after', 'After'), ('intraoral', 'Intraoral'), ('extraoral', 'Extraoral'), ('radiograph', 'Radiograph'), ('other', 'Other')], default='progress', max_length=20)),
                ('image', models.ImageField(upload_to=clinical.models._upload_orthodontic_photo)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('taken_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ortho_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='clinical.orthodonticcase')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='clinical.orthodonticvisit')),
            ],
            options={
                'ordering': ['-taken_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrthodonticDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('consent', 'Treatment Consent'), ('treatment_plan', 'Treatment Plan'), ('referral', 'Referral Letter'), ('radiograph', 'Radiograph'), ('study_model', 'Study Model'), ('cephalometric', 'Cephalometric Analysis'), ('photograph', 'Photograph'), ('pdf', 'PDF'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=clinical.models._upload_orthodontic_document)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ortho_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clinical.orthodonticcase')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
