# Generated by Django 4.2.11 on 2026-07-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_alter_orthodonticcase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='treatment_scope',
            field=models.CharField(choices=[('specific_teeth', 'Specific teeth'), ('whole_mouth', 'Whole mouth')], db_index=True, default='specific_teeth', max_length=20),
        ),
        migrations.AddField(
            model_name='recallschedule',
            name='preset',
            field=models.CharField(choices=[('six_weeks', '6 weeks'), ('six_months', '6 months'), ('custom', 'Custom date')], default='custom', max_length=20),
        ),
    ]
