# Generated by Django 4.2.11 on 2026-07-17 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinical', '0006_clinicalnote_treatment_scope_recallschedule_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='other_dentist_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='dentist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
