# Generated by Django 4.2.11 on 2026-07-18 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinical', '0008_orthodonticcase_contacted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orthodonticcase',
            name='contacted_at',
        ),
        migrations.RemoveField(
            model_name='orthodonticcase',
            name='linked_appointment',
        ),
        migrations.RemoveField(
            model_name='orthodonticcase',
            name='snoozed_until',
        ),
        migrations.AddField(
            model_name='recallschedule',
            name='contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recallschedule',
            name='linked_appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recall_schedule', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='recallschedule',
            name='snoozed_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orthodonticcase',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('retention', 'Retention'), ('completed', 'Completed'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='recallschedule',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('booked', 'Booked'), ('snoozed', 'Snoozed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], default='active', max_length=20),
        ),
    ]
