# Generated by Django 4.2.11 on 2026-07-24 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def normalize_legacy_reminders(apps, schema_editor):
    RecallSchedule = apps.get_model('clinical', 'RecallSchedule')
    RecallSchedule.objects.filter(recall_type='preventive').update(recall_type='scaling_polishing')
    RecallSchedule.objects.filter(status__in=['snoozed', 'missed']).update(status='active')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinical', '0009_remove_orthodonticcase_contacted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recallschedule',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='recallschedule',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recallschedule',
            name='archived_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recallschedule',
            name='booked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recallschedule',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recallschedule',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recallschedule',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recallschedule',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recallschedule',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recallschedule',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(normalize_legacy_reminders, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='recallschedule',
            name='recall_type',
            field=models.CharField(choices=[('scaling_polishing', 'Scaling & Polishing Recall'), ('orthodontic', 'Orthodontic Review'), ('root_canal', 'Root Canal Review'), ('extraction', 'Extraction Review'), ('treatment', 'Treatment Review'), ('follow_up', 'Follow-up'), ('examination', 'Recall Examination'), ('diagnosis', 'Diagnosis Review'), ('emergency', 'Emergency Review'), ('implant', 'Implant Review'), ('crown', 'Crown Review'), ('bridge', 'Bridge Review'), ('restoration', 'Restoration Review'), ('custom', 'Custom Review')], max_length=30),
        ),
        migrations.AlterField(
            model_name='recallschedule',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
