import {useCallback,useEffect,useMemo,useState} from 'react'
import {createRecall} from '../../services/clinical.service'
import {cancelReminder,getReminders,rescheduleReminder} from '../../services/appointments.service'

const types=[['scaling_polishing','Scaling & Polishing Recall'],['orthodontic','Orthodontic Review'],['root_canal','Root Canal Review'],['extraction','Extraction Review'],['treatment','Treatment Review'],['follow_up','Follow-up'],['examination','Recall Examination'],['custom','Custom Review']]
const presets=[['42','6 Weeks'],['90','3 Months'],['180','6 Months'],['365','12 Months'],['custom','Custom Date']]
const initial={recall_type:'examination',preset:'180',customDate:'',notes:''}
const iso=date=>date.toISOString().slice(0,10)

export default function ClinicalRecall({patient}){
 const [items,setItems]=useState([]),[form,setForm]=useState(initial),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[rescheduling,setRescheduling]=useState(null),[newDate,setNewDate]=useState(''),[reason,setReason]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');try{const data=await getReminders({patient:patient.id,ordering:'-created_at'});setItems(data.results||data||[])}catch{setError('Recall information could not be loaded.')}finally{setLoading(false)}},[patient.id])
 useEffect(()=>{load()},[load])
 const dueDate=useMemo(()=>{if(form.preset==='custom')return form.customDate;const date=new Date();date.setDate(date.getDate()+Number(form.preset));return iso(date)},[form.preset,form.customDate])
 const current=items.find(item=>!['completed','cancelled'].includes(item.status))||null
 async function submit(event){event.preventDefault();if(saving)return;if(!dueDate){setError('Choose a valid due date.');return}setSaving(true);setError('');try{await createRecall({patient:patient.id,recall_type:form.recall_type,due_date:dueDate,interval_days:Math.max(1,Math.round((new Date(dueDate)-new Date())/86400000)),preset:'custom',notes:form.notes});setStatus('Recall created successfully.');setForm(initial);await load()}catch(err){setError(err?.response?.data?.non_field_errors?.[0]||err?.response?.data?.detail||'Recall could not be saved.')}finally{setSaving(false)}}
 return <div className="space-y-4">
  <header className="rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">Recall</h2><p className="mt-1 text-sm text-slate-600">Manage clinical recall independently from the Clinical Note.</p></header>
  {error&&<div role="alert" className="rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}{status&&<div role="status" className="rounded-lg bg-green-50 p-3 text-green-800">{status}</div>}
  {loading?<div className="rounded-xl bg-white p-8">Loading recall…</div>:<>
   <section className="rounded-xl border bg-white p-5"><h3 className="font-bold">Current Recall</h3>{current?<div className="mt-3 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><p><span className="text-slate-500">Type</span><br/><b>{current.reminder_type_label}</b></p><p><span className="text-slate-500">Due date</span><br/><b>{current.due_date}</b></p><p><span className="text-slate-500">Status</span><br/><b className="capitalize">{current.status}</b></p><p><span className="text-slate-500">Appointment</span><br/><b>{current.appointment_date?`${current.appointment_date} ${current.appointment_time}`:'Not linked'}</b></p><div className="flex gap-3 sm:col-span-2 lg:col-span-4"><button onClick={()=>{setRescheduling(current);setNewDate('');setReason('')}} className="text-blue-700">Reschedule</button>{['active','contacted','confirmed'].includes(current.status)&&<button onClick={async()=>{const why=window.prompt('Cancellation reason');if(why){await cancelReminder(current.id,why);await load()}}} className="text-red-700">Cancel</button>}</div></div>:<p className="mt-3 text-sm text-slate-500">No active recall is recorded.</p>}</section>
   <form onSubmit={submit} className="rounded-xl border bg-white p-5"><h3 className="font-bold">Create Recall</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Recall Type<select value={form.recall_type} onChange={e=>setForm({...form,recall_type:e.target.value})} className="mt-1 w-full rounded border p-2">{types.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-medium">Due Date Option<select value={form.preset} onChange={e=>setForm({...form,preset:e.target.value})} className="mt-1 w-full rounded border p-2">{presets.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{form.preset==='custom'&&<label className="text-sm font-medium">Custom Date<input type="date" min={iso(new Date())} value={form.customDate} onChange={e=>setForm({...form,customDate:e.target.value})} className="mt-1 w-full rounded border p-2"/></label>}<label className="text-sm font-medium">Notes<textarea rows="3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="mt-1 w-full rounded border p-2"/></label></div><p className="mt-3 text-sm"><b>Calculated due date:</b> {dueDate||'Select a date'}</p><button disabled={saving||!dueDate} className="mt-4 rounded-lg bg-blue-700 px-4 py-2 font-semibold text-white disabled:bg-slate-300">{saving?'Creating…':'Create Recall'}</button></form>
   <section className="rounded-xl border bg-white p-5"><h3 className="font-bold">Recall History</h3>{items.length?<div className="mt-3 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr><th>Due date</th><th>Type</th><th>Status</th><th>Created</th><th>History</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-t"><td className="py-3">{item.due_date}</td><td>{item.reminder_type_label}</td><td className="capitalize">{item.status}</td><td>{item.created_at?new Date(item.created_at).toLocaleDateString():'—'}</td><td>{item.reschedule_history?.length||0} reschedule(s), {item.contact_history?.length||0} contact(s)</td></tr>)}</tbody></table></div>:<p className="mt-3 text-sm text-slate-500">No recall history.</p>}</section>
  </>}
  {rescheduling&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={async e=>{e.preventDefault();if(!newDate||!reason)return;await rescheduleReminder(rescheduling.id,{new_due_date:newDate,reason});setRescheduling(null);await load()}} className="w-full max-w-lg rounded-xl bg-white p-6"><h3 className="text-lg font-bold">Reschedule Recall</h3><p className="mt-2 text-sm">Current date: {rescheduling.due_date}</p><label className="mt-4 block text-sm">New date<input required type="date" value={newDate} onChange={e=>setNewDate(e.target.value)} className="mt-1 w-full rounded border p-2"/></label><label className="mt-4 block text-sm">Reason<textarea required value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 w-full rounded border p-2"/></label><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={()=>setRescheduling(null)}>Cancel</button><button className="rounded bg-blue-700 px-4 py-2 text-white">Save</button></div></form></div>}
 </div>
}
