# Generated by Django 4.2.11 on 2026-07-13 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0003_patient_ortho_interval_weeks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='scheduled', max_length=15)),
                ('chief_complaint', models.TextField(blank=True)),
                ('pre_appointment_notes', models.TextField(blank=True)),
                ('treatment_notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['scheduled_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('default_duration', models.PositiveSmallIntegerField(default=30, help_text='Minutes')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex colour for calendar', max_length=7)),
                ('requires_anesthesia', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'appointment_types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_days', models.JSONField(default=list, help_text="e.g. ['monday', 'wednesday']")),
                ('preferred_time_from', models.TimeField(blank=True, null=True)),
                ('preferred_time_to', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('scheduled', 'Scheduled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('appointment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.appointmenttype')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_entries', to='patients.patient')),
                ('preferred_dentist', models.ForeignKey(blank=True, limit_choices_to={'role': 'dentist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_patients', to=settings.AUTH_USER_MODEL)),
                ('scheduled_appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_waiting_list', to='appointments.appointment')),
            ],
            options={
                'db_table': 'waiting_list',
                'ordering': [models.Case(models.When(priority='urgent', then=0), models.When(priority='high', then=1), models.When(priority='normal', then=2), models.When(priority='low', then=3), default=4), 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.appointmenttype'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='dentist',
            field=models.ForeignKey(limit_choices_to={'role': 'dentist'}, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_date', 'dentist'], name='appointment_schedul_929460_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'scheduled_date'], name='appointment_patient_5455db_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['dentist', 'status'], name='appointment_dentist_7f7f66_idx'),
        ),
    ]
