# Generated by Django 4.2.11 on 2026-08-02 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='decline_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending_acceptance', 'Pending Acceptance'), ('accepted', 'Accepted'), ('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('blocked', 'Blocked'), ('awaiting_review', 'Awaiting Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived'), ('overdue', 'Overdue')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_accepted', 'Task Accepted'), ('task_declined', 'Task Declined'), ('task_completed', 'Task Completed'), ('task_blocked', 'Task Blocked'), ('task_overdue', 'Task Overdue'), ('task_reassigned', 'Task Reassigned'), ('task_deleted', 'Task Deleted')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=220)),
                ('message', models.CharField(max_length=320)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_notifications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.task')),
            ],
            options={
                'db_table': 'task_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='task_notifi_recipie_5ed820_idx'), models.Index(fields=['task', 'notification_type'], name='task_notifi_task_id_cccc27_idx')],
            },
        ),
    ]
