# Generated by Django 4.2.11 on 2026-08-02 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_task_accepted_at_task_decline_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='blocked_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='blocked_resolution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='blocker_owner',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='declined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='latest_progress_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='progress_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='waiting_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='waiting_resume_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='mime_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending_acceptance', 'Pending Acceptance'), ('accepted', 'Accepted'), ('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('blocked', 'Blocked'), ('awaiting_review', 'Awaiting Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('archived', 'Archived'), ('overdue', 'Overdue')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasknotification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_accepted', 'Task Accepted'), ('task_declined', 'Task Declined'), ('task_completed', 'Task Completed'), ('task_blocked', 'Task Blocked'), ('task_waiting', 'Task Waiting'), ('task_started', 'Task Started'), ('task_resumed', 'Task Resumed'), ('task_progress_update', 'Task Progress Update'), ('task_attachment_added', 'Task Attachment Added'), ('task_overdue', 'Task Overdue'), ('task_reassigned', 'Task Reassigned'), ('task_deleted', 'Task Deleted')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='TaskProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status_at_time', models.CharField(choices=[('pending_acceptance', 'Pending Acceptance'), ('accepted', 'Accepted'), ('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('blocked', 'Blocked'), ('awaiting_review', 'Awaiting Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('archived', 'Archived'), ('overdue', 'Overdue')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_progress_updates', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='tasks.task')),
            ],
            options={
                'db_table': 'task_progress_updates',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='progress_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.taskprogressupdate'),
        ),
        migrations.AddIndex(
            model_name='taskprogressupdate',
            index=models.Index(fields=['task', 'created_at'], name='task_progre_task_id_47f049_idx'),
        ),
    ]
