# Generated by Django 4.2.11 on 2026-08-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_accepted_by_task_blocked_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprogressupdate',
            name='event_type',
            field=models.CharField(db_index=True, default='note', max_length=40),
        ),
        migrations.AddField(
            model_name='taskprogressupdate',
            name='new_stage',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='taskprogressupdate',
            name='previous_stage',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='taskprogressupdate',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending_acceptance', 'Pending Acceptance'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('waiting_for_vendor', 'Waiting for Vendor'), ('waiting_for_staff', 'Waiting for Staff'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('not_started', 'Not Started (Legacy)'), ('waiting', 'Waiting (Legacy)'), ('blocked', 'Blocked (Legacy)'), ('awaiting_review', 'Awaiting Review (Legacy)'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('archived', 'Archived'), ('overdue', 'Overdue')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskprogressupdate',
            name='status_at_time',
            field=models.CharField(choices=[('pending_acceptance', 'Pending Acceptance'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('waiting_for_vendor', 'Waiting for Vendor'), ('waiting_for_staff', 'Waiting for Staff'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('not_started', 'Not Started (Legacy)'), ('waiting', 'Waiting (Legacy)'), ('blocked', 'Blocked (Legacy)'), ('awaiting_review', 'Awaiting Review (Legacy)'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('archived', 'Archived'), ('overdue', 'Overdue')], db_index=True, max_length=20),
        ),
    ]
