# Generated by Django 4.2.11 on 2026-07-15 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(db_index=True, max_length=80)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('message', models.CharField(max_length=255)),
                ('source_module', models.CharField(blank=True, db_index=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='security_al_status_9d0c83_idx'), models.Index(fields=['alert_type', 'created_at'], name='security_al_alert_t_3110ff_idx'), models.Index(fields=['user', 'created_at'], name='security_al_user_id_917922_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='login_attem_email_61a0cd_idx'), models.Index(fields=['success', 'created_at'], name='login_attem_success_965250_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_role', models.CharField(blank=True, db_index=True, max_length=40)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('resource_type', models.CharField(db_index=True, max_length=120)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('patient_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('request_method', models.CharField(blank=True, max_length=12)),
                ('endpoint', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('source_module', models.CharField(blank=True, db_index=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('event_hash', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'success'], name='audit_event_timesta_431d1d_idx'), models.Index(fields=['user', 'timestamp'], name='audit_event_user_id_69236c_idx'), models.Index(fields=['action', 'timestamp'], name='audit_event_action_db888c_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_event_resourc_917803_idx'), models.Index(fields=['patient_id', 'timestamp'], name='audit_event_patient_c28e0b_idx'), models.Index(fields=['source_module', 'timestamp'], name='audit_event_source__618dff_idx')],
            },
        ),
    ]
