# Generated by Django 4.2.11 on 2026-07-18 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_securityalert_loginattempt_auditevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='Beyond Smile Dental Clinic', max_length=200)),
                ('short_name', models.CharField(default='BSDC EMR', max_length=80)),
                ('tagline', models.CharField(blank=True, default='Dental Practice Platform', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('primary_colour', models.CharField(default='#2563eb', max_length=7)),
                ('secondary_colour', models.CharField(default='#0f172a', max_length=7)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('locale', models.CharField(default='en-NG', max_length=20)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinic_settings',
            },
        ),
    ]
